### ISSUE TITLE
win_service: ConvertTo-SecurityIdentifier fail split dotted domain name

### ISSUE THREAD

**Issue by east1k** [ansible-collections/ansible.windows#156]
##### SUMMARY
Function `ConvertTo-SecurityIdentifier` in module `win_service` split username `CONTOSO.COM\user` as
```
CONTOSO
COM\user
```
instead
```
CONTOSO.COM
user
```
Perhabs, problem is [selected row](https://github.com/ansible-collections/ansible.windows/blob/2cb34abac77eccd788cd0f9c9152281e6da7330d/plugins/modules/win_service.ps1#L111).
Maybe need change to `$nameSplit = $Name.Split('\', 2)` for fix.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

win_service

##### ANSIBLE VERSION

```paste below
ansible 2.10.3
  config file = /work/ansible.cfg
  configured module search path = ['/work/library']
  ansible python module location = /usr/local/lib/python3.6/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.6.10 (default, Apr 23 2020, 15:40:23) [GCC 6.3.0 20170516]
```

##### CONFIGURATION

```paste below
not matters
```

##### OS / ENVIRONMENT

- Windows 2019 Server

##### STEPS TO REPRODUCE

```yaml
  - win_service:
      name: TEST
      username: 'CONTOSO.COM\user'
      password: 'password'
      state: stopped
      path: test.exe
```

##### EXPECTED RESULTS

ok: [host] => changed=true

##### ACTUAL RESULTS

```paste below
The full traceback is:
Exception calling "Translate" with "1" argument(s): "Some or all identity references could not be translated."
At line:286 char:27
+ ...            $desiredSid = ConvertTo-SecurityIdentifier -Name $Username
+                              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [ConvertTo-SecurityIdentifier], MethodInvocationException
    + FullyQualifiedErrorId : IdentityNotMappedException,ConvertTo-SecurityIdentifier

ScriptStackTrace:
at ConvertTo-SecurityIdentifier, <No file>: line 124
at Set-ServiceAccount, <No file>: line 286
at <ScriptBlock>, <No file>: line 957

System.Management.Automation.MethodInvocationException: Exception calling "Translate" with "1" argument(s): "Some or all identity references could not be translated." ---> System.Security.Principal.IdentityNotMappedException: Some or all identity references could not be translated.
   at System.Security.Principal.NTAccount.Translate(IdentityReferenceCollection sourceAccounts, Type targetType, Boolean forceSuccess)
   at System.Security.Principal.NTAccount.Translate(Type targetType)
   at CallSite.Target(Closure , CallSite , Object , Type )
   --- End of inner exception stack trace ---
   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)
   at System.Management.Automation.PSScriptCmdlet.RunClause(Action`1 clause, Object dollarUnderbar, Object inputToProcess)
   at System.Management.Automation.PSScriptCmdlet.DoEndProcessing()
   at System.Management.Automation.CommandProcessorBase.Complete()
fatal: [kwb-delme1.dev.kontur.ru]: FAILED! => changed=false
  msg: 'Unhandled exception while executing module: Exception calling "Translate" with "1" argument(s): "Some or all identity references could not be translated."'
```

**Comment by jborean93** [comment]
While this should be fixed if you are referencing an account with the full realm you should be using the UPN format `user@CONTOSO.COM`. The Netlogon format you currently has if really designed for netbios domain names `CONTOSO` and while it should work it’s not the proper format.

**Comment by east1k** [comment]
I didn't know that, thanks.

**Comment by jborean93** [comment]
Thanks for the bug report, this has been fixed with https://github.com/ansible-collections/ansible.windows/pull/158 and will be part of the next release of this collection.
