### ISSUE TITLE
win_package not detecting previous installation

### ISSUE THREAD

**Issue by pokepoke81** [ansible-collections/ansible.windows#166]
When using creates_path and/or creates_service, Ansible is not always detecting the previous installation and tries installation again (which fails). 

I have tried removing creates_path and creates_service separately to see if the issue is with one of them and it didn't effect the outcome. This code block works for a different package though on the same endpoint. Why is it trying to install the package?

Code:
```
- name: Install Carbon Black Protection
  ansible.windows.win_package:
    path: \\server\ELC\Shared\IT Installs\Carbon Black Protection\Agent - Windows Deployment\disabled - allow updates.msi
    creates_path: C:\Program Files (x86)\Bit9\Parity Agent\Parity.exe
    creates_service: Parity
    state: present
  become: yes
  become_method: runas
  vars:
    ansible_become_user: [Redacted]
    ansible_become_password: [Redacted]
  register: cbp_install_state
  notify:
    - reboot windows
    - wait for connection
```

Output:
```
TASK [role_carbon_black_protection : Install Carbon Black Protection] **********
task path: /builds/company/project/playbooks/roles/role_carbon_black_protection/tasks/main.yml:7
Using module file /root/.ansible/collections/ansible_collections/ansible/windows/plugins/modules/win_package.ps1
Pipelining is enabled.
<server> ESTABLISH WINRM CONNECTION FOR USER: user on PORT 5986 TO server
EXEC (via pipeline wrapper)
The full traceback is:
Exception calling "OpenPackage" with "1" argument(s): "Another version of this product is already installed. Installation of this version cannot continue. To configure or remove the existing version of this product, use Add/Remove Programs on the Control Panel"
At line:1361 char:22
+     $packageStatus = Get-InstalledStatus @getParams
+                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-InstalledStatus], MethodInvocationException
    + FullyQualifiedErrorId : Win32Exception,Get-InstalledStatus
ScriptStackTrace:
at <ScriptBlock>, <No file>: line 741
at Get-InstalledStatus, <No file>: line 568
at <ScriptBlock>, <No file>: line 1361
System.Management.Automation.MethodInvocationException: Exception calling "OpenPackage" with "1" argument(s): "Another version of this product is already installed. Installation of this version cannot continue. To configure or remove the existing version of this product, use Add/Remove Programs on the Control Panel" ---> System.ComponentModel.Win32Exception: Another version of this product is already installed. Installation of this version cannot continue. To configure or remove the existing version of this product, use Add/Remove Programs on the Control Panel
   at Ansible.WinPackage.MsiHelper.OpenPackage(String packagePath) in c:\Users\Administrator\AppData\Local\Temp\ansible-moduletmp-132538099254226231-517784301\lg44zpkl.0.cs:line 359
   at CallSite.Target(Closure , CallSite , Type , String )
   --- End of inner exception stack trace ---
   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)
   at System.Management.Automation.PSScriptCmdlet.RunClause(Action`1 clause, Object dollarUnderbar, Object inputToProcess)
   at System.Management.Automation.PSScriptCmdlet.DoEndProcessing()
   at System.Management.Automation.CommandProcessorBase.Complete()
fatal: [server]: FAILED! => {
    "changed": false,
    "msg": "Unhandled exception while executing module: Exception calling \"OpenPackage\" with \"1\" argument(s): \"Another version of this product is already installed. Installation of this version cannot continue. To configure or remove the existing version of this product, use Add/Remove Programs on the Control Panel\""
}
```

**Comment by jborean93** [comment]
Sorry for the delay in getting back to you, when looking at the error message it seems like `win_package` is trying to open the install msi using [MsiOpenPackage](https://docs.microsoft.com/en-us/windows/win32/api/msi/nf-msi-msiopenpackagew) but that is failing and returning the error code you are seeing.

> Another version of this product is already installed. Installation of this version cannot continue. To configure or remove the existing version of this product, use Add/Remove Programs on the Control Panel

From reading online this seems to indicate that the product the msi represents is already installed on your host but was installed through a different package, maybe an older or newer version. I believe https://github.com/ansible-collections/ansible.windows/pull/175 should fix this problem in the product code detection and consider the package to be installed under these conditions. This won't upgrade the package if the existing one is older but that would ultimately be a new feature to add to win_package as it's not currently designed for that particular purpose.

**Comment by ty733420** [comment]
Why is it trying to open the install msi, at all, when creates_path / creates_service is set and those conditions are already satisfied?  I think that was the intent of the question.  We are seeing this behavior as well.
