### ISSUE TITLE
win_template doesn't work

### ISSUE THREAD

**Issue by man4red** [ansible-collections/ansible.windows#212]
##### SUMMARY

It seems that the recent changes broke win_template
https://github.com/ansible/ansible/commit/22330dd322634548e0f4d88aa9c5c017b7c04851

Looks like src/dest are messed up

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

win_template

##### ANSIBLE VERSION

```paste below
ansible [core 2.11.0rc2] 
  config file = /home/lemur/gitlab/ansible/ansible.cfg
  configured module search path = ['/home/lemur/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.8/site-packages/ansible
  ansible collection location = /home/lemur/gitlab/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.8.8 (default, Apr 12 2021, 14:03:57) [GCC 8.3.0]
  jinja version = 2.11.3
  libyaml = True
```

##### CONFIGURATION

```paste below
ANSIBLE_FORCE_COLOR(/home/lemur/gitlab/ansible/ansible.cfg) = True
COLLECTIONS_PATHS(/home/lemur/gitlab/ansible/ansible.cfg) = ['/home/lemur/gitlab/ansible/collections']
DEFAULT_BECOME(/home/lemur/gitlab/ansible/ansible.cfg) = True
DEFAULT_GATHERING(/home/lemur/gitlab/ansible/ansible.cfg) = smart
DEFAULT_HOST_LIST(/home/lemur/gitlab/ansible/ansible.cfg) = ['/home/lemur/gitlab/ansible/inventories']
DEFAULT_JINJA2_EXTENSIONS(/home/lemur/gitlab/ansible/ansible.cfg) = jinja2.ext.loopcontrols
DEFAULT_LOAD_CALLBACK_PLUGINS(/home/lemur/gitlab/ansible/ansible.cfg) = True
DEFAULT_PRIVATE_KEY_FILE(/home/lemur/gitlab/ansible/ansible.cfg) = /ansible/.ssh/id_rsa
DEFAULT_ROLES_PATH(/home/lemur/gitlab/ansible/ansible.cfg) = ['/home/lemur/gitlab/ansible/galaxy-roles', '/
DEFAULT_STDOUT_CALLBACK(/home/lemur/gitlab/ansible/ansible.cfg) = yaml
HOST_KEY_CHECKING(/home/lemur/gitlab/ansible/ansible.cfg) = False
PLAYBOOK_DIR(/home/lemur/gitlab/ansible/ansible.cfg) = /home/lemur/gitlab/ansible
RETRY_FILES_ENABLED(/home/lemur/gitlab/ansible/ansible.cfg) = False
```

##### OS / ENVIRONMENT

Debian GNU/Linux 10 (buster)

##### STEPS TO REPRODUCE

```yaml
- name: Copy file
  win_template:
    src: "templates/file.j2"
    dest: "C:\\path\\file.ps1"
```

##### EXPECTED RESULTS

win_template works

##### ACTUAL RESULTS

```paste below
The full traceback is:
Traceback (most recent call last):
  File "/home/lemur/gitlab/ansible/collections/ansible_collections/ansible/windows/plugins/action/win_template.py", line 126, in run
    temp_vars.update(generate_ansible_template_vars(source, dest))
  File "/usr/local/lib/python3.8/site-packages/ansible/template/__init__.py", line 113, in generate_ansible_template_vars
    template_uid = pwd.getpwuid(os.stat(b_path).st_uid).pw_name
FileNotFoundError: [Errno 2] No such file or directory: b'C:\\path\\file.ps1'
fatal: [windows-server]: FAILED! => changed=false 
  msg: 'FileNotFoundError: [Errno 2] No such file or directory: b''C:\\path\\file.ps1'''
```

and if we'd look closer
adding that to ansible/template/__init__.py
```
print(fullpath)
print(path)
```

shows
```
C:\path\file.ps1
/home/user/ansible/roles/test/templates/file.j2
```

**Comment by jborean93** [comment]
Thanks for the report, this was fixed with the latest release with https://github.com/ansible-collections/ansible.windows/pull/200 and if you upgrade the collection to v1.5.0 it will contain the fix.
