### ISSUE TITLE
win_update: Installation failed when getting KB number within get_update_info

### ISSUE THREAD

**Issue by mafl79** [ansible-collections/ansible.windows#247]
##### SUMMARY
win_update module fails when getting update info for custom patches.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
- win_update

##### ANSIBLE VERSION
```
ansible [core 2.11.2] 
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/rundeck/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.8/site-packages/ansible
  ansible collection location = /home/rundeck/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.8.10 (default, Jul  6 2021, 14:01:14) [GCC 7.5.0]
  jinja version = 3.0.1
  libyaml = True
```

##### COLLECTION VERSION
```
ansible.windows               1.7.0
```

##### CONFIGURATION
```
DEFAULT_ROLES_PATH(/etc/ansible/ansible.cfg) = ['/home/rundeck/server/data/ansible/roles']
DEFAULT_STDOUT_CALLBACK(/etc/ansible/ansible.cfg) = yaml
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False
```

##### OS / ENVIRONMENT
- Ubuntu 18.04.5 LTS [Ansible Provision Server]
- Windows 2016/2019 Server [Guest OS]

##### STEPS TO REPRODUCE
With a custom update on WSUS with custom KB number e.g.:
```
    "id":  "98e5d323-2749-467a-aebb-37268d09ae50",
    "title":  "Update - .Net Framework 4.8.0",
    "description":  "Update - .Net Framework 4.8.0 x64",
    "kb":  [
               "KBNET4800"
           ],
    "type":  "Software",
    "deployment_action":  "Installation",
    "auto_select_on_websites":  false,
    "browse_only":  false,
    "revision_number":  2,
    "categories":  [
                       "AutoUpdate",
                       "Security Updates"
                   ],
    "is_installed":  false,
    "is_hidden":  false,
    "is_present":  false,
    "reboot_required":  false,
    "impact":  "Normal",
    "reboot_behaviour":  "CanRequestReboot",
    "is_beta":  false,
    "is_downloaded":  false,
    "is_mandatory":  false,
    "is_uninstallable":  false,
    "auto_selection":  "LetWindowsUpdateDecide",
    "auto_download":  "LetWindowsUpdateDecide"
```
The playbook:
```
- name: Install all security, critical, and rollup updates
  win_updates:
    category_names:
      - SecurityUpdates
      - CriticalUpdates
      - UpdateRollups
    reboot: yes
    state: installed
    reboot_timeout: 3600
```

##### EXPECTED RESULTS
Should complete the update successfully

##### ACTUAL RESULTS
Failed with the following traceback:
```
<XXX> Starting update task
Using module file /usr/local/lib/python3.8/site-packages/ansible_collections/ansible/windows/plugins/modules/win_updates.ps1
Pipelining is enabled.
EXEC (via pipeline wrapper)
<XXX> Starting polling for update results
EXEC (via pipeline wrapper)
<XXX> Received final progress result from update task
EXEC (via pipeline wrapper)
The full traceback is:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/ansible/executor/task_executor.py", line 158, in run
    res = self._execute()
  File "/usr/local/lib/python3.8/site-packages/ansible/executor/task_executor.py", line 582, in _execute
    result = self._handler.run(task_vars=variables)
  File "/usr/local/lib/python3.8/site-packages/ansible_collections/ansible/windows/plugins/action/win_updates.py", line 782, in run
    update_info = self._get_update_info(update_id)
  File "/usr/local/lib/python3.8/site-packages/ansible_collections/ansible/windows/plugins/action/win_updates.py", line 996, in _get_update_info
    'kb': [int(v[2:]) for v in raw_info['kb']],
  File "/usr/local/lib/python3.8/site-packages/ansible_collections/ansible/windows/plugins/action/win_updates.py", line 996, in <listcomp>
    'kb': [int(v[2:]) for v in raw_info['kb']],
ValueError: invalid literal for int() with base 10: 'NET4800'
fatal: [XXX]: FAILED! => 
  msg: Unexpected failure during module execution.
  stdout: ''
```

**Comment by jborean93** [comment]
I guess that answers the question as to whether KBs can have non-integer values. Will create a fix for this momentarily.

**Comment by jborean93** [comment]
Thanks for the pickup on this, https://github.com/ansible-collections/ansible.windows/pull/248 should resolve this problem.

**Comment by mafl79** [comment]
Thanks a lot for your quick response and for fixing that.
