### ISSUE TITLE
win_user_right module fails to add SeServiceLogonRight on a domain joined machine

### ISSUE THREAD

**Issue by mitkko** [ansible-collections/ansible.windows#316]
##### SUMMARY
In the scenario where a new local administrator is being created for a machine, part of a domain, when subsequent attempt is made to add some rights to the new user account, the `win_user_right` module fails with an unexpected error and exception.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
`win_user_right`

##### ANSIBLE VERSION

```paste below
ansible [core 2.11.6]
  config file = /home/mitkko/.ansible.cfg
  configured module search path = ['/home/mitkko/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/mitkko/.local/lib/python3.8/site-packages/ansible
  ansible collection location = /home/mitkko/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/mitkko/.local/bin/ansible
  python version = 3.8.10 (default, Sep 28 2021, 16:10:42) [GCC 9.3.0]
  jinja version = 3.0.2
  libyaml = True
```

##### COLLECTION VERSION

```paste below
# /home/mitkko/.ansible/collections/ansible_collections
Collection        Version
----------------- -------
ansible.windows   1.8.0
community.windows 1.8.0
```

##### CONFIGURATION

```paste below
SHOW_CUSTOM_STATS(/home/mitkko/.ansible.cfg) = True
```

##### OS / ENVIRONMENT

Windows Server 2019 Datacenter
```
Windows Server 2019 Datacenter
Version: 1809
Product Id : 00430-00000-00000-AA063
```

##### STEPS TO REPRODUCE

```yaml
---
- hosts: C9DA0000508
  name: PL

  gather_facts: no

  tasks:

  - name: Create user
    win_user:
      name: svcUser01
      fullname: svcUser01
      password: changeit
      state: present
      groups_action: add
      groups:
        - Users
        - Administrators

  - name: Add user to Log on as a service
    win_user_right:
      name: SeServiceLogonRight
      users:
        - svcUser01
      action: add
```

##### EXPECTED RESULTS

Service logon right is added to the newly created user account.

##### ACTUAL RESULTS

```paste below
mitkko@W5191699:~$ ansible-playbook -i ~/ansible/inventories/hada/dev-inventory.yml ~/src/hada-test.yml -vvv --limit dev
ansible-playbook [core 2.11.6]
  config file = /home/mitkko/.ansible.cfg
  configured module search path = ['/home/mitkko/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/mitkko/.local/lib/python3.8/site-packages/ansible
  ansible collection location = /home/mitkko/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/mitkko/.local/bin/ansible-playbook
  python version = 3.8.10 (default, Sep 28 2021, 16:10:42) [GCC 9.3.0]
  jinja version = 3.0.2
  libyaml = True
Using /home/mitkko/.ansible.cfg as config file
host_list declined parsing /home/mitkko/ansible/inventories/hada/dev-inventory.yml as it did not pass its verify_file() method
Parsed /home/mitkko/ansible/inventories/hada/dev-inventory.yml inventory source with yaml plugin
redirecting (type: modules) ansible.builtin.win_user to ansible.windows.win_user
redirecting (type: modules) ansible.builtin.win_user_right to ansible.windows.win_user_right
redirecting (type: modules) ansible.builtin.win_user_right to ansible.windows.win_user_right
Skipping callback 'default', as we already have a stdout callback.
Skipping callback 'minimal', as we already have a stdout callback.
Skipping callback 'oneline', as we already have a stdout callback.

PLAYBOOK: hada-test.yml *********************************************************************************************************************************************************************************************************************
1 plays in /home/mitkko/src/hada-test.yml

PLAY [PL] ******************************************************************************************************************************************************************************************************************
META: ran handlers

TASK [Create user] **************************************************************************************************************************************************************************************************************************
task path: /home/mitkko/src/hada-test.yml:13
redirecting (type: modules) ansible.builtin.win_user to ansible.windows.win_user
Using module file /home/mitkko/.ansible/collections/ansible_collections/ansible/windows/plugins/modules/win_user.ps1
Pipelining is enabled.
<10.188.27.5> ESTABLISH WINRM CONNECTION FOR USER: c9user on PORT 5986 TO 10.188.27.5
EXEC (via pipeline wrapper)
changed: [C9DA0000508] => {
    "account_disabled": false,
    "account_locked": false,
    "changed": true,
    "description": "",
    "fullname": "svcUser01",
    "groups": [
        {
            "name": "Users",
            "path": "WinNT://PLHADA/C9DA0000508/Users"
        },
        {
            "name": "Administrators",
            "path": "WinNT://PLHADA/C9DA0000508/Administrators"
        }
    ],
    "invocation": {
        "module_args": {
            "account_disabled": null,
            "account_locked": null,
            "description": null,
            "fullname": "svcUser01",
            "groups": [
                "Users",
                "Administrators"
            ],
            "groups_action": "add",
            "home_directory": null,
            "login_script": null,
            "name": "svcUser01",
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "password_expired": null,
            "password_never_expires": true,
            "profile": null,
            "state": "present",
            "update_password": "always",
            "user_cannot_change_password": null
        }
    },
    "name": "svcUser01",
    "password_expired": false,
    "password_never_expires": true,
    "path": "WinNT://PLHADA/C9DA0000508/svcUser01",
    "sid": "S-1-5-21-1287971095-97545420-2541722864-1015",
    "state": "present",
    "user_cannot_change_password": false
}

TASK [Add user to Log on as a service] ******************************************************************************************************************************************************************************************************
task path: /home/mitkko/src/hada-test.yml:25
redirecting (type: modules) ansible.builtin.win_user_right to ansible.windows.win_user_right
Using module file /home/mitkko/.ansible/collections/ansible_collections/ansible/windows/plugins/modules/win_user_right.ps1
Pipelining is enabled.
<10.188.27.5> ESTABLISH WINRM CONNECTION FOR USER: c9user on PORT 5986 TO 10.188.27.5
EXEC (via pipeline wrapper)
The full traceback is:
Exception calling "Translate" with "1" argument(s): "The trust relationship between this workstation and the primary domain failed.
"
At line:346 char:34
+ $userSids = [String[]]@($users | ConvertTo-SecurityIdentifier | ForEa ...
+                                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [ConvertTo-SecurityIdentifier], MethodInvocationException
    + FullyQualifiedErrorId : SystemException,ConvertTo-SecurityIdentifier

ScriptStackTrace:
at ConvertTo-SecurityIdentifier<Process>, <No file>: line 337
at <ScriptBlock>, <No file>: line 346

System.Management.Automation.MethodInvocationException: Exception calling "Translate" with "1" argument(s): "The trust relationship between this workstation and the primary domain failed.
" ---> System.SystemException: The trust relationship between this workstation and the primary domain failed.

   at System.Security.Principal.NTAccount.TranslateToSids(IdentityReferenceCollection sourceAccounts, Boolean& someFailed)
   at System.Security.Principal.NTAccount.Translate(IdentityReferenceCollection sourceAccounts, Type targetType, Boolean forceSuccess)
   at System.Security.Principal.NTAccount.Translate(Type targetType)
   at CallSite.Target(Closure , CallSite , Object , Type )
   --- End of inner exception stack trace ---
   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)
   at System.Management.Automation.PSScriptCmdlet.RunClause(Action`1 clause, Object dollarUnderbar, Object inputToProcess)
   at System.Management.Automation.PSScriptCmdlet.DoProcessRecord()
   at System.Management.Automation.CommandProcessor.ProcessRecord()
fatal: [C9DA0000508]: FAILED! => {
    "changed": false,
    "msg": "Unhandled exception while executing module: Exception calling \"Translate\" with \"1\" argument(s): \"The trust relationship between this workstation and the primary domain failed.\r\n\""
}

PLAY RECAP **********************************************************************************************************************************************************************************************************************************
C9DA0000508 : ok=1    changed=1    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
```

**Comment by jborean93** [comment]
Looks like the code needs to handle cases where it cannot translate the SID a bit better, thanks for the issue report.

**Comment by jborean93** [comment]
When starting to look at the code here I don't believe there is anything we can do in this situation. Essentially the code is trying to do the following:

```powershell
$account = New-Object -TypeName System.Security.Principal.NTAccount -ArgumentList "svcUser01"
$account.Translate([System.Security.Principal.SecurityIdentifier])
```

In this case the `NTAccount` constructor that it is using is https://docs.microsoft.com/en-us/dotnet/api/system.security.principal.ntaccount.-ctor?view=net-6.0#System_Security_Principal_NTAccount__ctor_System_String_ and it's up to .NET/Win32 on where it attempts to translate the value. In the absence of a domain name (`SERVER\username`) it looks like Win32 attempts to lookup the account on the domain and ultimately in your case there is a trust issue.

There are 2 ways you can work around this:

* Pass in the account's SID registered from `win_user`

```yaml
- name: Create user
  win_user:
    name: svcUser01
    fullname: svcUser01
    password: changeit
    state: present
    groups_action: add
    groups:
    - Users
    - Administrators
  register: service_user

- name: Add user to Log on as a service
  win_user_right:
    name: SeServiceLogonRight
    users:
    - '{{ service_user.sid }}'
    action: add
```

* Use the `.\` prefix in the task to explicitly tell the code to lookup the account using the localhost rather than the domain https://github.com/ansible-collections/ansible.windows/blob/bdb3c56f4c0532446081ed80b7b28fca597f2d60/plugins/modules/win_user_right.ps1#L309-L311

```yaml
- name: Add user to Log on as a service
  win_user_right:
    name: SeServiceLogonRight
    users:
    - .\svcUser01
    action: add
```

I'll open a PR to update the docs to clarify this situation a bit more but unfortunately I don't see how I could really change this code without breaking the lookup order that is currently in place.
