### ISSUE TITLE
The term 'Get-AppxPackage' is not recognized as the name of a cmdlet

### ISSUE THREAD

**Issue by basictheprogram** [ansible-collections/ansible.windows#362]
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
ansible.windows.win_package

##### ANSIBLE VERSION

```paste below
ansible [core 2.12.4]
  config file = /Users/tanner/projects/ansible/src/playbooks/celadonsystems.com/ansible.cfg
  configured module search path = ['/Users/tanner/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/tanner/projects/ansible/lib/python3.9/site-packages/ansible
  ansible collection location = /Users/tanner/.ansible/collections:/usr/share/ansible/collections
  executable location = /Users/tanner/projects/ansible/bin/ansible
  python version = 3.9.13 (main, May 24 2022, 21:13:51) [Clang 13.1.6 (clang-1316.0.21.2)]
  jinja version = 3.0.3
  libyaml = True
```

##### COLLECTION VERSION

```paste below

# /Users/tanner/.ansible/collections/ansible_collections
Collection      Version
--------------- -------
ansible.windows 1.10.0
```

##### CONFIGURATION

```paste below
<nothing>
```

##### OS / ENVIRONMENT

Ansible controller
```
$ sw_vers
ProductName:	macOS
ProductVersion:	12.4
BuildVersion:	21F79
```
Ansible managed host
```
Windows Server 2008 R2 
Version 6.1 (Build 7601: Service Pack 1)
```

##### STEPS TO REPRODUCE

```yaml
- name: uninstall Crystal Reports 2008 Runtime SP2
  ansible.windows.win_package:
    product_id: '{C484CC8D-03CF-4022-89C4-DB4F02E8A15B}'
    state: absent
```

##### EXPECTED RESULTS

Ansible will uninstall  Crystal Reports 2008 Runtime SP2 if installed

##### ACTUAL RESULTS

```paste below
TASK [win_syspro : uninstall Crystal Reports 2008 Runtime SP2] *****************
task path: /Users/tanner/projects/ansible/src/playbooks/roles/win_syspro/tasks/main.yml:35
Using module file /Users/tanner/.ansible/collections/ansible_collections/ansible/windows/plugins/modules/win_package.ps1
Pipelining is enabled.
<appserver.corp.celadonsystems.com> ESTABLISH WINRM CONNECTION FOR USER: Administrator@CORP.CELADONSYSTEMS.COM on PORT 5986 TO appserver.corp.celadonsystems.com
EXEC (via pipeline wrapper)
The full traceback is:
The term 'Get-AppxPackage' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1449 char:22
+     $packageStatus = Get-InstalledStatus @getParams
+                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Get-AppxPackage:String) [Get-InstalledStatus], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException,Get-InstalledStatus

ScriptStackTrace:
at <ScriptBlock>, <No file>: line 942
at Get-InstalledStatus, <No file>: line 600
at <ScriptBlock>, <No file>: line 1449

System.Management.Automation.CommandNotFoundException: The term 'Get-AppxPackage' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)
   at System.Management.Automation.PSScriptCmdlet.RunClause(Action`1 clause, Object dollarUnderbar, Object inputToProcess)
   at System.Management.Automation.PSScriptCmdlet.DoEndProcessing()
   at System.Management.Automation.CommandProcessorBase.Complete()
fatal: [appserver.corp.celadonsystems.com]: FAILED! => {
    "changed": false,
    "msg": "Unhandled exception while executing module: The term 'Get-AppxPackage' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again."
}
```
Been a few months since I've run this playbook and the last time I was on Ansible 2.9 but I read this issue more like the 
Get-AppxPackage is not installed on Windows Server 2008 R2 but I cannot figure out for the life of me how this worked.

**Comment by jborean93** [comment]
It looks to be quite simple to just ignore the appx/msix files when running on these older hosts that are missing the cmdlet so I'll probably push through a PR sometime soon that does just that.

In saying that support for Server 2008 and 2008 R2 was dropped when Microsoft dropped support for those hosts (outside of the extended Azure offering). This was done when Ansible 2.10 was released as per the changelog entry at https://github.com/ansible/ansible/blob/stable-2.10/changelogs/CHANGELOG-v2.10.rst#minor-changes-11

> Windows - add deprecation notice in the Windows setup module when running on Server 2008, 2008 R2, and Windows 7

We even have a warning raised by the setup module when running on these old hosts that state this https://github.com/ansible-collections/ansible.windows/blob/b14e8420b903aec8e9b83d62075d10325a4852da/plugins/modules/setup.ps1#L45-L51.

We do not test these collections against these Windows versions and you will most likely come across more scenarios like this were new features are added to support things present in newer Windows versions but not older ones. We cannot guarantee that modules in this collection will continue to work for Server 2008 and 2008 R2 going forward.
