### ISSUE TITLE
win_service errors with Win32ErrorCode 87 - 0x00000057

### ISSUE THREAD

**Issue by pau1ie** [ansible-collections/ansible.windows#415]
##### SUMMARY

I am installing Peoplesoft, which in turn installs Tuxedo. I need to change the Windows service to run as a particular user and start automatically. Using win_service for this works in Ansible 2.9.27, but doesn't work with Ansible Galaxy.

I have redacted username, password and hostnames in the pasted output, hopefully this doesn't cause confusion. I am updating the service to run using the same username and password as I am using to connect with Ansible.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

win_service

##### ANSIBLE VERSION

```paste below
ansible [core 2.12.2]
  config file = /home/user1/scripts/ansible-dev/ansible.cfg
  configured module search path = ['/home/user1/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.8/site-packages/ansible
  ansible collection location = /home/user1/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.8.12 (default, Sep 16 2021, 10:46:05) [GCC 8.5.0 20210514 (Red Hat 8.5.0-3)]
  jinja version = 2.10.3
  libyaml = True
```

##### COLLECTION VERSION

```paste below
# /home/user1/.ansible/collections/ansible_collections
Collection        Version
----------------- -------
community.windows 1.11.0 
```

##### CONFIGURATION

```paste below
CALLBACKS_ENABLED(/home/user1/scripts/ansible-dev/ansible.cfg) = ['profile_tasks']
DEFAULT_ACTION_PLUGIN_PATH(/home/user1/scripts/ansible-dev/ansible.cfg) = ['/home/user1/scripts/ansible-dev/plugins/action', '/home/user1/scripts/ansible-dev/plugins/action']
DEFAULT_FILTER_PLUGIN_PATH(/home/user1/scripts/ansible-dev/ansible.cfg) = ['/home/user1/scripts/ansible-dev/plugins/filter', '/home/user1/scripts/ansible-dev/plugins/filter']
DEFAULT_ROLES_PATH(env: ANSIBLE_ROLES_PATH) = ['/home/user1/scripts/camsis-ansible-oracle-nfs', '/home/user1/scripts/test']
DEFAULT_TIMEOUT(/home/user1/scripts/ansible-dev/ansible.cfg) = 60
HOST_KEY_CHECKING(/home/user1/scripts/ansible-dev/ansible.cfg) = False
```

##### OS / ENVIRONMENT

Controller: Red Hat Enterprise Linux release 8.6 (Ootpa)

Managed VM 1: Windows Server 2016 
Managed VM 2: Windows Server 2019

##### STEPS TO REPRODUCE

Apologies, I have been unable to create a reproducible this test case, which suggests I have been unable to discover something about the way  Oracle creates the service. It is notable that the problematic services have spaces in their names, but simply creating a service with a space in the name does not cause this issue to manifest itself when attempting to update the service using Ansible. 

I also tried to debug the issue to see if I could discover the error, but despite [following the procedure](https://docs.ansible.com/ansible/latest/dev_guide/developing_modules_general_windows.html#windows-debugging) I get an error. Attempting to set ANSIBLE_KEEP_REMOTE_FILES also results in an error. Unfortunately I don't understand Windows enough to be able to debug this myself. I also tried to find a way to export the service definition as generated by the installer, but did not find a way to do that. I'd be grateful for any assistance in building a test case or getting the debug process to work.

Inventory:
```yaml
all:
  children:
    winps:
      hosts:
        windowsvm:
      vars:
        ansible_connection: winrm
        ansible_winrm_server_cert_validation: ignore
        ansible_user: win_user
        ansible_password: "Password123"
```
Command and error message

```
$ ansible -i inventory -m win_service -a 'name="TUXEDO 12.2.2.0.0_VS2017 Listener on Port 3050" start_mode=auto username="windowsvm\username" password="Password123"' windowsvm
```

##### EXPECTED RESULTS

The service is updated to be started automatically with the supplied username and password, without errors.

##### ACTUAL RESULTS

```paste below
ansible [core 2.12.2]
  config file = /home/user1/scripts/ansible-dev/ansible.cfg
  configured module search path = ['/home/user1/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.8/site-packages/ansible
  ansible collection location = /home/user1/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.8.12 (default, Sep 16 2021, 10:46:05) [GCC 8.5.0 20210514 (Red Hat 8.5.0-3)]
  jinja version = 2.10.3
  libyaml = True
Using /home/user1/scripts/ansible-dev/ansible.cfg as config file
[DEPRECATION WARNING]: [defaults]callback_whitelist option, normalizing names to new standard, 
use callbacks_enabled instead. This feature will be removed from ansible-core in version 2.15. 
Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
setting up inventory plugins
host_list declined parsing /home/user1/scripts/ansible-dev/inventories/testenv as it did not pass its verify_file() method
script declined parsing /home/user1/scripts/ansible-dev/inventories/testenv as it did not pass its verify_file() method
auto declined parsing /home/user1/scripts/ansible-dev/inventories/testenv as it did not pass its verify_file() method
Parsed /home/user1/scripts/ansible-dev/inventories/testenv inventory source with yaml plugin
Loading callback plugin minimal of type stdout, v2.0 from /usr/lib/python3.8/site-packages/ansible/plugins/callback/minimal.py
redirecting (type: callback) ansible.builtin.profile_tasks to ansible.posix.profile_tasks
Loading collection ansible.posix from /home/user1/.ansible/collections/ansible_collections/ansible/posix
Skipping callback 'default', as we already have a stdout callback.
Skipping callback 'minimal', as we already have a stdout callback.
Skipping callback 'oneline', as we already have a stdout callback.
META: ran handlers
redirecting (type: modules) ansible.builtin.win_service to ansible.windows.win_service
Loading collection ansible.windows from /home/user1/.ansible/collections/ansible_collections/ansible/windows
Using module file /home/user1/.ansible/collections/ansible_collections/ansible/windows/plugins/modules/win_service.ps1
Pipelining is enabled.
<windowsvm> ESTABLISH WINRM CONNECTION FOR USER: win_user on PORT 5986 TO windowsvm
EXEC (via pipeline wrapper)
The full traceback is:
Exception setting "Account": "Failed to change service config (The parameter is incorrect, Win32ErrorCode 87 - 0x00000057)"
At line:1038 char:13
+             Set-ServiceAccount -Username $username -Password $passwor ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Set-ServiceAccount], SetValueInvocationException
    + FullyQualifiedErrorId : ExceptionWhenSetting,Set-ServiceAccount

ScriptStackTrace:
at Set-ServiceAccount, <No file>: line 325
at <ScriptBlock>, <No file>: line 1038

System.Management.Automation.SetValueInvocationException: Exception setting "Account": "Failed to change service config (The parameter is incorrect, Win32ErrorCode 87 - 0x00000057)" ---> ansible_collections.ansible.windows.plugins.module_utils.SCManager.ServiceManagerException: Failed to change service config (The parameter is incorrect, Win32ErrorCode 87 - 0x00000057)
   at ansible_collections.ansible.windows.plugins.module_utils.SCManager.Service.ChangeServiceConfig(ServiceType serviceType, ServiceStartType startType, ErrorControl errorControl, String binaryPath, String loadOrderGroup, List`1 dependencies, String startName, String password, String displayName) in c:\Users\win_user\AppData\Local\Temp\hwjmebk0.0.cs:line 1306
   at ansible_collections.ansible.windows.plugins.module_utils.SCManager.Service.set_Account(IdentityReference value) in c:\Users\win_user\AppData\Local\Temp\hwjmebk0.0.cs:line 762
   at CallSite.Target(Closure , CallSite , Service , Object )
   --- End of inner exception stack trace ---
   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)
   at System.Management.Automation.PSScriptCmdlet.RunClause(Action`1 clause, Object dollarUnderbar, Object inputToProcess)
   at System.Management.Automation.PSScriptCmdlet.DoEndProcessing()
   at System.Management.Automation.CommandProcessorBase.Complete()
windowsvm | FAILED! => {
    "changed": false,
    "msg": "Unhandled exception while executing module: Exception setting \"Account\": \"Failed to change service config (The parameter is incorrect, Win32ErrorCode 87 - 0x00000057)\""
}
```

**Comment by pau1ie** [comment]
Thanks for looking into this issue. I noticed the issue only happens if the service is running when I try to update the user. I added another play to stop the service before editing the user, and now my role works again. 

Something like this:
```
---
- name: Service issue test case.
  hosts: winps

  tasks:
  - name: Stop the service
    win_service:
      name: TUXEDO 12.2.2.0.0_VS2017 Listener on Port 3050
      start_mode: auto
      state: stopped

  - name: Fix user running the service
    win_service:
      name: TUXEDO 12.2.2.0.0_VS2017 Listener on Port 3050
      start_mode: auto
      username: "{{ ansible_host }}\\{{ ansible_user }}"
      password: "{{ ansible_password }}"
```

Here is the output of the debug just in case it is still useful:

```
ok: [windowsvm] => {
    "service_info.services[0]": {
        "checkpoint": 0,
        "controls_accepted": [
            "stop"
        ],
        "dependencies": [],
        "dependency_of": [],
        "description": null,
        "desktop_interact": false,
        "display_name": "TListen 12.2.2.0.0_VS2017(Port: 3050)",
        "error_control": "normal",
        "failure_actions": [],
        "failure_actions_on_non_crash_failure": false,
        "failure_command": null,
        "failure_reboot_msg": null,
        "failure_reset_period_sec": 0,
        "launch_protection": "none",
        "load_order_group": "",
        "name": "TUXEDO 12.2.2.0.0_VS2017 Listener on Port 3050",
        "path": "C:\\psft\\pt\\bea\\tuxedo\\tuxedo12.2.2.0.0_VS2017\\bin\\slisten.exe",
        "pre_shutdown_timeout_ms": 180000,
        "preferred_node": null,
        "process_id": 2276,
        "required_privileges": [],
        "service_exit_code": 0,
        "service_flags": [],
        "service_type": "win32_own_process",
        "sid_info": "none",
        "start_mode": "auto",
        "state": "started",
        "triggers": [],
        "username": "NT AUTHORITY\\SYSTEM",
        "wait_hint_ms": 0,
        "win32_exit_code": 0
    }
}
```

I have sorted out my problem, so I will leave it up to you as to what to do with this issue.

**Comment by jborean93** [comment]
It is perplexing, for now I think we will close it as I cannot replicate the problem and you have a workaround. If this does come up again please feel free to open a new issue and we can go from there.
