### ISSUE TITLE
_reboot.py change created syntax error

### ISSUE THREAD

**Issue by ryokubaka** [ansible-collections/ansible.windows#470]
I am using the latest Windows collection to install an application using the `win_package` module. However, despite the module working, it errors out with the block below. This seems to be related to the latest commit to the _reboot.py plugin.

I am hard-coding the collection version 1.12.0 to get around this error for now.

Error block:

```
ERROR! Unexpected Exception, this is probably a bug: invalid syntax (_reboot.py, line 70)
the full traceback was:

Traceback (most recent call last):
  File "/usr/bin/ansible-playbook", line 123, in <module>
    exit_code = cli.run()
  File "/usr/lib/python2.7/site-packages/ansible/cli/playbook.py", line 127, in run
    results = pbex.run()
  File "/usr/lib/python2.7/site-packages/ansible/executor/playbook_executor.py", line 169, in run
    result = self._tqm.run(play=play)
  File "/usr/lib/python2.7/site-packages/ansible/executor/task_queue_manager.py", line 244, in run
    play_return = strategy.run(iterator, play_context)
  File "/usr/lib/python2.7/site-packages/ansible/plugins/strategy/linear.py", line 248, in run
    action = action_loader.get(task.action, class_only=True)
  File "/usr/lib/python2.7/site-packages/ansible/plugins/loader.py", line 552, in get
    self._module_cache[path] = self._load_module_source(name, path)
  File "/usr/lib/python2.7/site-packages/ansible/plugins/loader.py", line 530, in _load_module_source
    module = imp.load_source(to_native(full_name), to_native(path), module_file)
  File "/var/lib/awx/.ansible/collections/ansible_collections/ansible/windows/plugins/action/win_updates.py", line 32, in <module>
    from ..plugin_utils._reboot import reboot_host
  File "/usr/lib/python2.7/site-packages/ansible/utils/collection_loader.py", line 107, in load_module
    mod = self._find_module(fullname, None, load=True)[1]
  File "/usr/lib/python2.7/site-packages/ansible/utils/collection_loader.py", line 221, in _find_module
    code_object = compile(source=source, filename=source_path, mode='exec', flags=0, dont_inherit=True)
  File "/var/lib/awx/.ansible/collections/ansible_collections/ansible/windows/plugins/plugin_utils/_reboot.py", line 70
    task_action: str,
               ^
SyntaxError: invalid syntax
```

Referenced line: https://github.com/ansible-collections/ansible.windows/blob/9bd3bf896fd72111d96aa7a910867c28c0e1faa5/plugins/plugin_utils/_reboot.py#L70

**Comment by jborean93** [comment]
The collection since `1.12.0` has had a minimum version of Ansible 2.12 as per https://github.com/ansible-collections/ansible.windows/blob/main/meta/runtime.yml. Ansible 2.12 requires at least Python 3.8 as per https://docs.ansible.com/ansible/latest/installation_guide/intro_installation.html#node-requirement-summary. You are using Python 2.7 hence the syntax error. You either need to

* Stay with the collection version 1.12.0, or
* Upgrade your Python version and Ansible version to 2.12.0

Just an FYI Ansible versions 2.11 and older are no longer supported hence why the bump in minimum versions.
