### ISSUE TITLE
win_updates failed with "The process cannot access the file 'output.txt' because it is being used by another process."

### ISSUE THREAD

**Issue by hiyokotaisa** [ansible-collections/ansible.windows#490]
##### SUMMARY

When I tried to run win_updates for Windows Server, it failed intermittently with  `"The process cannot access the file 'C:\\\\Users\\\\test\\\\AppData\\\\Local\\\\Te\\r\\nmp\\\\ansible-tmp-1677489180.7922058-38-162156186645130\\\\output.txt' because it is being used by another process.`

It seems `output.txt` is used by multiple process but I cannot identify why this happen. I tried to put pause module before run win_updates but there is no difference.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

win_updates

##### ANSIBLE VERSION

```paste below
core 2.14.0
```

##### COLLECTION VERSION

```paste below

```

##### STEPS TO REPRODUCE

Running following task for windows server
```yaml
    - name : Windows Update
      win_updates:
        category_names: ["CriticalUpdates", "DefinitionUpdates", "SecurityUpdates", "UpdateRollups", "Updates"]
        reboot: no
        reboot_timeout: 1200
        reject_list: ["Microsoft Silverlight"]
        server_selection: "default"
        skip_optional: no
        state: installed
```

##### EXPECTED RESULTS

win_updates run without issue.

##### ACTUAL RESULTS

```
<windows> Starting polling for update results
EXEC (via pipeline wrapper)
[WARNING]: Unknown failure when polling update result - attempting to cancel
task: Failed to poll update task, see rc, stdout, stderr for more info
EXEC (via pipeline wrapper)
EXEC (via pipeline wrapper)
The full traceback is:
Traceback (most recent call last):
  File "/usr/share/ansible/collections/ansible_collections/ansible/windows/plugins/action/win_updates.py", line 760, in run
    result = self._run_sync(task_vars, module_options, reboot, reboot_timeout)
  File "/usr/share/ansible/collections/ansible_collections/ansible/windows/plugins/action/win_updates.py", line 834, in _run_sync
    update_result = self._run_updates(task_vars, module_options, poll_script_path, cancel_script_path)
  File "/usr/share/ansible/collections/ansible_collections/ansible/windows/plugins/action/win_updates.py", line 931, in _run_updates
    entries, offset = self._poll_result(poll_script_path, output_path, offset)
  File "/usr/share/ansible/collections/ansible_collections/ansible/windows/plugins/action/win_updates.py", line 984, in _poll_result
    raise _ReturnResultException(msg, rc=rc, stdout=stdout, stderr=stderr)
ansible_collections.ansible.windows.plugins.action.win_updates._ReturnResultException: Failed to poll update task, see rc, stdout, stderr for more info
fatal: [windows]: FAILED! => {
    "changed": false,
    "failed_update_count": 0,
    "filtered_updates": {},
    "found_update_count": 0,
    "installed_update_count": 0,
    "msg": "Failed to poll update task, see rc, stdout, stderr for more info",
    "rc": 1,
    "stderr": "Exception calling \\"Open\\" with \\"4\\" argument(s): \\"The process cannot access the file 'C:\\\\Users\\\\test\\\\AppData\\\\Local\\\\Te\\r\\nmp\\\\ansible-tmp-1677489180.7922058-38-162156186645130\\\\output.txt' because it is being used by another process.\\"\\r\\nAt line:2 char:138\\r\\n+ ... .ps1' -Raw; &([ScriptBlock]::Create($cmd)) -OutputPath 'C:\\\\Users\\\\test ...\\r\\n+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\\r\\n    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException\\r\\n    + FullyQualifiedErrorId : IOException",
    "stdout": "",
    "updates": {}
}
```

**Comment by jborean93** [comment]
@hiyokotaisa I've opened https://github.com/ansible-collections/ansible.windows/pull/494 which fixes the only code I could see that would stop the polling task from opening a read handle. It is theoretically possible for this race condition to occur but I can't guarantee it's the same as what's happening in this particular scenario.

Unfortunately without being able to reproduce the error myself I can only work on with what I can see in the code. We can always revisit the issue again in the future if it still occurs.

**Comment by jborean93** [comment]
Thanks I'll reopen the issue if it is still present. Ultimately your failure occurs in this script https://github.com/ansible-collections/ansible.windows/blob/16d2359d7c5a3e6f80a209d3634c6edc550c18f8/plugins/action/win_updates.py#L75 and due to the complicated way it is run it looses some of the stack trace information. I'll have to try and look more into it but the last time I checked I couldn't find any other process that would lock the file for reading. Can you share your Windows version you are testing against?

**Comment by ChandlerSwift** [comment]
Sounds great! I'm continuing to try to familiarize myself with this, but I rarely use Ansible against Windows (honestly, I generally try my best to avoid Windows!) so I'm pretty clueless about Powershell and such. That said, let me know if there's any more information I can find.

I think all the servers that have seen this issue have been running Windows Server 2019, though there may have been 2016 and 2022 servers in the mix. I can try to keep better notes if you think that's a factor.

Figuring I might as well leave as much information as possible, here's what Ansible thinks about this machine! It's a VM running in Azure, for what it's worth. I've tried to redact all personally incriminating information, but if I was overzealous or there's more info that's helpful, let me know and I'll add it.

```yaml
---
- hosts: all
  tasks:
  - ansible.builtin.debug:
      var: ansible_facts
```
yields:
```json
{
    "ansible_facts": {
        "architecture": "64-bit",
        "architecture2": "x86_64",
        "bios_date": "12/07/2018",
        "bios_version": "090008",
        "date_time": {
            "date": "2023-04-14",
            "day": "14",
            "epoch": "1681508735.65539",
            "epoch_int": 1681508736,
            "epoch_local": "1681508735.65539",
            "hour": "21",
            "iso8601": "2023-04-14T21:45:35Z",
            "iso8601_basic": "20230414T214535655387",
            "iso8601_basic_short": "20230414T214535",
            "iso8601_micro": "2023-04-14T21:45:35.655387Z",
            "minute": "45",
            "month": "04",
            "second": "35",
            "time": "21:45:35",
            "tz": "UTC",
            "tz_offset": "+00:00",
            "weekday": "Friday",
            "weekday_number": "5",
            "weeknumber": "14",
            "year": "2023"
        },
        "distribution": "Microsoft Windows Server 2019 Datacenter",
        "distribution_major_version": "10",
        "distribution_version": "10.0.17763.0",
        "domain": "domain.local",
        "env": {
            "ALLUSERSPROFILE": "C:\\ProgramData",
            "APPDATA": "C:\\Users\\user\\AppData\\Roaming",
            "COMPUTERNAME": "hostname",
            "ChocolateyInstall": "C:\\ProgramData\\chocolatey",
            "ChocolateyLastPathUpdate": "Tue Sep 22 16:54:06 2020",
            "ComSpec": "C:\\windows\\system32\\cmd.exe",
            "CommonProgramFiles": "C:\\Program Files\\Common Files",
            "CommonProgramFiles(x86)": "C:\\Program Files (x86)\\Common Files",
            "CommonProgramW6432": "C:\\Program Files\\Common Files",
            "DriverData": "C:\\Windows\\System32\\Drivers\\DriverData",
            "LOCALAPPDATA": "C:\\Users\\user\\AppData\\Local",
            "NUMBER_OF_PROCESSORS": "2",
            "OS": "Windows_NT",
            "PATHEXT": ".COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.CPL",
            "PROCESSOR_ARCHITECTURE": "AMD64",
            "PROCESSOR_IDENTIFIER": "Intel64 Family 6 Model 85 Stepping 7, GenuineIntel",
            "PROCESSOR_LEVEL": "6",
            "PROCESSOR_REVISION": "5507",
            "PROMPT": "$P$G",
            "PSExecutionPolicyPreference": "Unrestricted",
            "PSModulePath": "C:\\Users\\user\\Documents\\WindowsPowerShell\\Modules;C:\\Program Files\\WindowsPowerShell\\Modules;C:\\windows\\system32\\WindowsPowerShell\\v1.0\\Modules;C:\\Program Files\\Microsoft Monitoring Agent\\Agent\\PowerShell\\;C:\\Program Files\\Microsoft Monitoring Agent\\Agent\\AzureAutomation\\7.3.1455.3",
            "PUBLIC": "C:\\Users\\Public",
            "Path": "C:\\Python10\\Scripts\\;C:\\Python10\\;C:\\windows\\system32;C:\\windows;C:\\windows\\System32\\Wbem;C:\\windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\windows\\System32\\OpenSSH\\;C:\\ProgramData\\chocolatey\\bin;C:\\Program Files\\PowerShell\\6\\;C:\\Program Files\\Zabbix Agent;C:\\Program Files\\Microsoft SQL Server\\160\\DAC\\bin;C:\\Users\\user\\AppData\\Local\\Microsoft\\WindowsApps",
            "ProgramData": "C:\\ProgramData",
            "ProgramFiles": "C:\\Program Files",
            "ProgramFiles(x86)": "C:\\Program Files (x86)",
            "ProgramW6432": "C:\\Program Files",
            "SystemDrive": "C:",
            "SystemRoot": "C:\\windows",
            "TEMP": "C:\\Users\\user\\AppData\\Local\\Temp",
            "TMP": "C:\\Users\\user\\AppData\\Local\\Temp",
            "USERDOMAIN": "hostname",
            "USERNAME": "user",
            "USERPROFILE": "C:\\Users\\user",
            "cloudProvider": "Azure",
            "windir": "C:\\windows"
        },
        "fqdn": "hostname.domain.local",
        "gather_subset": [
            "all"
        ],
        "hostname": "hostname",
        "interfaces": [
            {
                "connection_name": "Ethernet 2",
                "default_gateway": "...",
                "dns_domain": "reddog.microsoft.com",
                "interface_index": 4,
                "interface_name": "Microsoft Hyper-V Network Adapter #2",
                "ipv4": {
                    "address": "...",
                    "prefix": "..."
                },
                "ipv6": {},
                "macaddress": "...",
                "mtu": 1500,
                "speed": 50000
            }
        ],
        "ip_addresses": [
            "..."
        ],
        "kernel": "10.0.17763.0",
        "lastboot": "2023-04-14 00:33:02Z",
        "machine_id": "...",
        "memfree_mb": 5626,
        "memtotal_mb": 8192,
        "module_setup": true,
        "netbios_name": "hostname",
        "nodename": "hostname.domain.local",
        "os_family": "Windows",
        "os_installation_type": "Server",
        "os_name": "Microsoft Windows Server 2019 Datacenter",
        "os_product_type": "server",
        "owner_contact": "",
        "owner_name": "",
        "pagefilefree_mb": 1053,
        "pagefiletotal_mb": 1280,
        "powershell_version": 5,
        "processor": [
            "0",
            "GenuineIntel",
            "Intel(R) Xeon(R) Platinum 8272CL CPU @ 2.60GHz",
            "1",
            "GenuineIntel",
            "Intel(R) Xeon(R) Platinum 8272CL CPU @ 2.60GHz"
        ],
        "processor_cores": 1,
        "processor_count": 2,
        "processor_threads_per_core": 2,
        "processor_vcpus": 2,
        "product_name": "Virtual Machine",
        "product_serial": "...",
        "reboot_pending": false,
        "swaptotal_mb": 0,
        "system": "Win32NT",
        "system_description": "",
        "system_vendor": "Microsoft Corporation",
        "uptime_seconds": 76355,
        "user_dir": "C:\\Users\\user",
        "user_gecos": "",
        "user_id": "user",
        "user_sid": "...",
        "virtualization_role": "guest",
        "virtualization_type": "Hyper-V",
        "win_rm_certificate_expires": "2023-11-16 21:53:05",
        "windows_domain": "domain.local",
        "windows_domain_member": true,
        "windows_domain_role": "Member server"
    }
}
```

**Comment by ChandlerSwift** [comment]
@hiyokotaisa We're seeing signs that point towards this maybe being an Azure-exclusive issue. Is there any chance that you're also running into this issue on a VM in Azure?

**Comment by chibs89** [comment]
Hi, we see this also on Windows 11 now. We only run it on Azure VMs. On Windows 10 22H2 there is no issue. 
Also following sysprep command does not work anymore if it helps.  
ansible.windows.win_command: C:\Windows\System32\Sysprep\Sysprep.exe /generalize /oobe /quiet /mode:vm /shutdown
The machine does not shutdown anymore. This also only happens at Windows 11 on Azure.

**Comment by jborean93** [comment]
I tried running the module on both Windows 10 22H2 and Windows 11 in Azure but I couldn't replicate the problem. I'm honestly unsure what would be causing it but the PR https://github.com/ansible-collections/ansible.windows/pull/509 adds a retry mechanism to the code that is failing here to hopefully alleviate the problem if it's just a small race condition with another process opening the file.

**Comment by hiyokotaisa** [comment]
We are still facing same issue after updating the collection that is merged with the fix. Might be we have other factor to cause this race condition.
